# This is an example Starter pipeline configuration
# Use a skeleton to build, test and deploy using manual and parallel steps
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: rust:buster

pipelines:
  branches:
    master:
      - step:
          name: 'Delete old binary'
          script:
            - pipe: atlassian/ssh-run:0.3.0
              variables:
                SSH_USER: $PADOUK_USER
                SERVER: $PADOUK_IP
                COMMAND: 'rm -f /home/cyprien/.bin/ctprods.new'
                MODE: 'command'
      - step:
          script:
            - rustup target add x86_64-unknown-linux-musl
            - apt -y update
            - apt install -y musl-tools musl-dev gcc-multilib build-essential
            - echo "Building..."; cargo build --target x86_64-unknown-linux-musl --release
            - mv target/release/ctprods target/release/ctprods.new
          artifacts:
            - target/release/ctprods.new
          caches:
            - cargo
            - rust-target
      - step:
          name: 'Deployment to Production'
          deployment: production
          script:
            - pipe: atlassian/ssh-run:0.3.0
              variables:
                SSH_USER: $PADOUK_USER
                SERVER: $PADOUK_IP
                COMMAND: 'rm -f /home/cyprien/.bin/ctprods.new'
                MODE: 'command'
            - pipe: atlassian/scp-deploy:1.0.1
              variables:
                USER: $PADOUK_USER
                SERVER: $PADOUK_IP
                REMOTE_PATH: '/home/cyprien/.bin'
                LOCAL_PATH: $BITBUCKET_CLONE_DIR/target/release/ctprods.new
                DEBUG: 'true'
            - pipe: atlassian/ssh-run:0.3.0
              variables:
                SSH_USER: $PADOUK_USER
                SERVER: $PADOUK_IP
                COMMAND: 'rm -f /home/cyprien/.bin/ctprods.bak && mv /home/cyprien/.bin/ctprods /home/cyprien/.bin/ctprods.bak && mv /home/cyprien/.bin/ctprods.new /home/cyprien/.bin/ctprods && sudo service ctprods restart'
                MODE: 'command'
definitions:
  caches:
    cargo: /usr/local/cargo
    rust-target: $BITBUCKET_CLONE_DIR/target
